<a href="https://colab.research.google.com/github/sksatvikkumar/DATA110-Cybersecurity-Capstone/blob/main/Lab_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_train = pd.read_csv('/content/train_titanic.csv')
df_test = pd.read_csv('/content/test_titanic.csv')

In [ ]:
df_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df_train = df_train.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [ ]:
df_test = df_test.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [ ]:
df_train.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
# Sample Dataset
data = {
    "Age": [20, 21, 22, 23, 24, 25, 26],
    "Marks": [85, np.nan, 78, 90, np.nan, 88, 95],
    "City": ["Delhi", "Mumbai", np.nan, "Delhi", "Chennai", "Mumbai", np.nan]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original Dataset\n")
print(df)

Original Dataset

   Age  Marks     City
0   20   85.0    Delhi
1   21    NaN   Mumbai
2   22   78.0      NaN
3   23   90.0    Delhi
4   24    NaN  Chennai
5   25   88.0   Mumbai
6   26   95.0      NaN

In [ ]:
# Drop rows with missing values
df_drop_rows = df.dropna()

print("\nRows after dropping missing values")
print(df_drop_rows)

Rows after dropping missing values
   Age  Marks    City
0   20   85.0   Delhi
3   23   90.0   Delhi
5   25   88.0  Mumbai

In [ ]:
# Drop columns with missing values
df_drop_col = df.dropna(axis=1)

print("\nColumns after dropping missing values")
print(df_drop_col)

Columns after dropping missing values
   Age
0   20
1   21
2   22
3   23
4   24
5   25
6   26

In [ ]:
# Fill missing values with a constant
df_constant = df.fillna(99999)

print("\nFill with Constant (99999)")
print(df_constant)

Fill with Constant (99999)
   Age    Marks     City
0   20     85.0    Delhi
1   21  99999.0   Mumbai
2   22     78.0    99999
3   23     90.0    Delhi
4   24  99999.0  Chennai
5   25     88.0   Mumbai
6   26     95.0    99999

In [ ]:
# Fill missing values with NA
df_constant = df.fillna("NA")

print(df_constant)

   Age Marks     City
0   20  85.0    Delhi
1   21    NA   Mumbai
2   22  78.0       NA
3   23  90.0    Delhi
4   24    NA  Chennai
5   25  88.0   Mumbai
6   26  95.0       NA

In [ ]:
# Mean Imputation
df_mean = df.copy()
df_mean["Age"] = df_mean["Age"].fillna(df_mean["Age"].mean())
df_mean["Marks"] = df_mean["Marks"].fillna(df_mean["Marks"].mean())

print("\nMean Imputation")
print(df_mean)

Mean Imputation
   Age  Marks     City
0   20   85.0    Delhi
1   21   87.2   Mumbai
2   22   78.0      NaN
3   23   90.0    Delhi
4   24   87.2  Chennai
5   25   88.0   Mumbai
6   26   95.0      NaN

In [ ]:
# Median Imputation
df_median = df.copy()
df_median["Age"] = df_median["Age"].fillna(df_median["Age"].median())
df_median["Marks"] = df_median["Marks"].fillna(df_median["Marks"].median())

print("\nMedian Imputation")
print(df_median)

Median Imputation
   Age  Marks     City
0   20   85.0    Delhi
1   21   88.0   Mumbai
2   22   78.0      NaN
3   23   90.0    Delhi
4   24   88.0  Chennai
5   25   88.0   Mumbai
6   26   95.0      NaN

In [ ]:
# Mode Imputation
df_mode = df.copy()
df_mode["City"] = df_mode["City"].fillna(df_mode["City"].mode()[0])

print("\nMode Imputation")
print(df_mode)

Mode Imputation
   Age  Marks     City
0   20   85.0    Delhi
1   21    NaN   Mumbai
2   22   78.0    Delhi
3   23   90.0    Delhi
4   24    NaN  Chennai
5   25   88.0   Mumbai
6   26   95.0    Delhi

In [ ]:
# Forward Fill
df_ffill = df.ffill()
print("\nForward Fill")
print(df_ffill)

Forward Fill
   Age  Marks     City
0   20   85.0    Delhi
1   21   85.0   Mumbai
2   22   78.0   Mumbai
3   23   90.0    Delhi
4   24   90.0  Chennai
5   25   88.0   Mumbai
6   26   95.0   Mumbai

In [ ]:
# Backward Fill
df_bfill = df.bfill()
print("\nBackward Fill")
print(df_bfill)

Backward Fill
   Age  Marks     City
0   20   85.0    Delhi
1   21   78.0   Mumbai
2   22   78.0    Delhi
3   23   90.0    Delhi
4   24   88.0  Chennai
5   25   88.0   Mumbai
6   26   95.0      NaN

In [ ]:
# Linear Intercolation
df_interpolate = df.interpolate()
df_interpolate["Age"] = df_interpolate["Age"].interpolate()
df_interpolate["Marks"] = df_interpolate["Marks"].interpolate()
print("\nLinear Intercolation")
print(df_interpolate)

Linear Intercolation
   Age  Marks     City
0   20   85.0    Delhi
1   21   81.5   Mumbai
2   22   78.0      NaN
3   23   90.0    Delhi
4   24   89.0  Chennai
5   25   88.0   Mumbai
6   26   95.0      NaN

/tmp/ipykernel_2625/2338535024.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolate = df.interpolate()

In [ ]:
# Specific Value Imputation

In [ ]:
# Random Imputation
df_random = df.copy()

for col in ["Age", "Marks"]:
    missing = df_random[col].isnull()
    random_values = df_random[col].dropna().sample(missing.sum(), replace=True).values
    df_random.loc[missing, col] = random_values

print("\nRandom Imputation")
print(df_random)

Random Imputation
   Age  Marks     City
0   20   85.0    Delhi
1   21   90.0   Mumbai
2   22   78.0      NaN
3   23   90.0    Delhi
4   24   85.0  Chennai
5   25   88.0   Mumbai
6   26   95.0      NaN

In [ ]:
df_train['Embarked'] = df_train['Embarked'].fillna('S')

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [ ]:
avg_age_df_train = df_train['Age'].mean()
std_age_df_train = df_train['Age'].std()
count_age_train = df_train['Age'].isnull().sum()
rand1 = np.random.randint(avg_age_df_train - std_age_df_train, avg_age_df_train + std_age_df_train, size = count_age_train)
df_train.loc[df_train['Age'].isnull(), 'Age'] = rand1

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    object
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB